# Generated by Django 4.2.4 on 2023-08-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('flight_departure_time', models.CharField()),
                ('flight_arrival_time', models.CharField()),
                ('flight_departure_from', models.CharField(max_length=20)),
                ('flight_destination', models.CharField(max_length=20)),
                ('no_of_seats', models.IntegerField(default=60)),
                ('flight_price', models.FloatField()),
                ('flight_duration', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.flights')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.user')),
            ],
        ),
    ]
