# Generated by Django 4.2.4 on 2023-08-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbookings',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
